"area:core":
  - changed-files:
      - any-glob-to-any-file: packages/core/**

"area:server":
  - changed-files:
      - any-glob-to-any-file: packages/server/**

"area:react":
  - changed-files:
      - any-glob-to-any-file: packages/react/**

"area:ui":
  - changed-files:
      - any-glob-to-any-file:
          - packages/ui/**
          - registry.json

"area:db":
  - changed-files:
      - any-glob-to-any-file: packages/db/**

"area:cli":
  - changed-files:
      - any-glob-to-any-file:
          - packages/cli/**
          - templates/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - apps/docs/**
          - docs/**

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**
